/* cmds.c */
void do_slope(char arg[256]);
void do_trig(char arg[256]);
void do_rcph(char arg[256]);
void do_col_power(char arg[256]);
void do_power(char arg[256]);
void do_recip(char arg[256]);
void do_log(char arg[256]);
void do_ExpLin(char arg[256]);
void do_Poly4(char arg[256]);
void do_gensin(char arg[256]);
void do_genexp(char arg[256]);
void do_rclow(char arg[256]);
void do_scchisqr(char arg[256]);
void do_chisqr(char arg[256]);
void do_normal(char arg[256]);
void do_Power2(char arg[256]);
void do_Power1(char arg[256]);
void do_ln(char arg[256]);
void do_exp(char arg[256]);
void do_deriv(char arg[256]);
void do_vc(char arg[256]);
void do_rgt(char arg[256]);
void do_cgt(char arg[256]);
void do_ec(char arg[256]);
void do_cs(char arg[256]);
void do_polyfit(char arg[256]);
void do_sort(char arg[256]);
void do_interpolate(char arg[256]);
void do_math(char arg[256]);
void do_mathint(char arg[256]);
void math_final(char *name_arg, char *unit_arg);
void do_r_spike(char arg[256]);
void do_positive(char arg[256]);
void do_compress(char arg[256]);
void do_r_mean(char arg[256]);
void do_z_min(char arg[256]);
void do_z_max(char arg[256]);
void do_trend(char arg[256]);
void do_trend_a(char arg[256]);
void do_final_trend(void);
void do_r_trend_input(char arg[256]);
void do_r_trend_comp(char arg[256]);
void do_r_trend_final(void);
void do_findint(char arg[256]);
void do_summation(char arg[256]);
void do_curv(char arg[256]);
void do_peak(char arg[256]);
void do_decimat(char arg[256]);
void do_pdf(char arg[256]);
void do_pdfauto(char arg[256]);
void do_pdf1(void);
void do_pdf2(void);
void do_r_row_col(char arg[256]);
void do_r_row(char arg[256]);
void do_r_row_final(int l, int col1, int first, int last);
void do_comment(char arg[256]);
void do_name(char arg[256]);
void do_r_col(int col);
void do_zero_all(char arg[256]);
void do_zero(char arg[256]);
void do_offset_int(char arg[256]);
void do_offset(char arg[256]);
void simplex_info(void);
void do_simplex(char arg[256]);
void do_head(char arg[256]);
void do_getaschead(char arg[256]);
void do_examin(char arg[256]);
void print_rsm_help_info(void);
void do_rsm(char arg[256]);
void print_cm_help_info(void);
void do_cm(char arg[256]);
void do_mem(char arg[256]);
void do_median_smooth(char arg[256]);
void do_smooth(char arg[256]);
void do_typeall(char arg[256]);
void do_type(char arg[256]);
void do_type_final(void);
void do_stats(char arg[256]);
void do_qi(char arg[256]);
void do_qi_mvs(char arg[256]);
void do_qi_final(void);
void do_qi_help(void);
void do_scm(char arg[256]);
void do_simp_weight_l2(char arg[256]);
void do_simp_weight(char arg[256]);
void do_simp_weight_final(void);
void do_scm_next(void);
void do_scm_1(char arg[256]);
void do_scm_2(void);
void do_scm_help(void);
void do_scm_info(void);
